# Generated by Django 4.0.1 on 2022-04-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
