# Generated by Django 4.0.1 on 2022-01-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('text', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
