# Generated by Django 4.0.1 on 2022-01-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(),
        ),
    ]
