# Generated by Django 4.0.1 on 2022-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_management', '0004_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
