# Generated by Django 4.0.1 on 2022-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_management', '0008_alter_note_date_alter_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image_url',
            field=models.ImageField(default=1, upload_to='notes/'),
            preserve_default=False,
        ),
    ]
