# Generated by Django 4.0.1 on 2022-02-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_management', '0009_note_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
